USE customer_behaver;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    SUM(`purchase_amount(usd)`) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT
	customer_id,
    age,
    gender,
    `purchase_amount(usd)`
from customer
where 
`discount_applied` = "Yes" 
And `purchase_amount(usd)` >= 
	(SELECT avg(`purchase_amount(usd)`) from customer)
    order by `purchase_amount(usd)`DESC;

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    round(AVG(review_rating),2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
	shipping_type,
	round(AVG(`purchase_amount(usd)`),2)  
from
customer
where shipping_type in ('Standard','Express Shipping')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT 
	subscription_status,
    COUNT(customer_id) as total_customer,
    ROUND(avg(`purchase_amount(usd)`), 2) as Avrage_Spend,
    ROUND(SUM(`purchase_amount(usd)`), 2) as Total_revenu
FROM customer
group by subscription_status
order by Total_revenu,Avrage_Spend;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        SUM(CASE 
                WHEN discount_applied = 'Yes' THEN 1 
                ELSE 0 
            END) * 100.0 / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
SELECT 
    customer_segment,
    COUNT(*) AS total_customers
FROM (
    SELECT 
        customer_id,
        CASE 
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
) AS customer_segments
GROUP BY customer_segment;
-- Q8. What are the top 3 most purchased products within each category? 
 WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;